[[containers]]
source = "ghcr.io/chronopax/bazzite-p1000:latest"

[[customizations.filesystem]]
mountpoint = "/"
minsize = "10 GiB"

[customizations.installer]
unattended = false
sudo-nopasswd = ["wheel"]
